version: "3"

services:
  blaster:
    build: 
      context: ./
    ports:
      - "5000:80"
    depends_on:
      - header-injector-proxy
      - auth-proxy
      - teamservice
    environment: 
      - BLASTER_CAPABILITYSERVICE_API_URL=http://teamservice:3000
      - BLASTER_IAMROLESERVICE_API_URL=http://iamroleservice:3000
  header-injector-proxy:
    build: 
      context: ./fake_dependencies/header-injector-proxy
    ports:
      - "5002:50802"
    depends_on:
      - auth-proxy
    environment:
      - FORWARD_ADDRESS=auth-proxy:50800
  auth-proxy:
    build: 
      context: ./src/auth-proxy
    ports:
      - "5001:50800"
    environment:
      - FORWARD_ADDRESS=blaster:80
  teamservice:
    build: 
      context: ./fake_dependencies/teamservice
    ports:
      - "50900:3000"
  iamroleservice:
    build: 
      context: ./fake_dependencies/iamroleservice
    ports:
      - "50901:3000"
  tika:
    build: 
      context: ./fake_dependencies/tika
    ports:
      - "50902:3000"